global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "mongodb"
    static_configs:
      - targets: [ "host.docker.internal:9216" ]
        labels:
          service_type: "mongodb"
  - job_name: "mysql"
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
  - job_name: "rabbitmq"
    static_configs:
      - targets: [ "host.docker.internal:15692" ]