apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    env: prod
    owner: tomcat
spec:
  selector:
    project: tomcat  # Selecting Pods with those labels
  ports:
    - name: web-api
      protocol: TCP
      port: 8088       # Port on Load Balancer
      targetPort: 8080 # Port on Pod
  type: LoadBalancer
