apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fe
  labels:
    app: sample-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      project: sample-fe
  template:
    metadata:
      labels:
        project: sample-fe  # Service will look for those Pods labels
    spec:
      containers:
        - name: sample-fe
          image: tertalex/sentinel-sample-fe:latest
          ports:
            - containerPort: 80