apiVersion: v1
kind: Service
metadata:
  name: sample-fe
  labels:
    env: prod
    owner: tert.alex
spec:
  selector:
    project: sample-fe  # Selecting Pods with those labels
  ports:
    - name: web-listener
      protocol: TCP
      port: 8087      # Port on Load Balancer
      targetPort: 80  # Port on Pod
  type: LoadBalancer
